### ISSUE TITLE
Skillable - List of Needed Fixes

### ISSUE THREAD

**Issue by Lanse505** [Lanse505/Skillable-2#1]
High Priority:
- [ ] Make Skill Registration Extendable
- [ ] Make Trait/Ability Registration Extendable(To New and Old Skills)

Medium Priority:
- [ ] Add a Level-based Stagger Cost List (See: https://github.com/Vazkii/Skillable/issues/13)
- [ ] Fix "Perfect Recover" Trait (See: https://github.com/Vazkii/Skillable/issues/18)

Low Priority:
- [ ] Look into https://github.com/Vazkii/Skillable/issues/5
- [ ] Look into https://github.com/Vazkii/Skillable/issues/20
- [ ] Maybe Look into https://github.com/Vazkii/Skillable/issues/10
